# Generated by Django 3.1.3 on 2020-11-12 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=128)),
                ('street', models.CharField(blank=True, max_length=128)),
                ('district', models.CharField(choices=[('TVM', 'Thiruvananthapuram'), ('KLM', 'Kollam'), ('PTM', 'Pathanamthitta'), ('ALP', 'Alappuzha'), ('KTM', 'Kottayam'), ('IDK', 'Idukki'), ('EKM', 'Ernakulam'), ('TSR', 'Thrissur'), ('MLP', 'Malappuram'), ('PKD', 'Palakkad'), ('MLP', 'Wayanad'), ('KZD', 'Kozhikode'), ('KNR', 'Kannur'), ('KSD', 'Kasargod')], max_length=30)),
                ('landline', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^[\\d]{3,4}[\\-\\s]*[\\d]{6,7}$')])),
                ('secondary_contact', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
